@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(reiziger, "Reiziger", "Stelt reizen samen en beheert deze")
Person(medewerker, "Medewerker", "Helpt bij samenstellen en boeken van reizen")

System(triptop, "TripTop", "Applicatie voor het samenstellen en beheren van reizen")
System_Ext(intern, "LeafletJS", "Kaarten Systeem")

Rel(reiziger, triptop, "Maakt reisaanvraag, bekijkt voorstellen")
Rel(medewerker, triptop, "Beheert reizen en maakt boekingen")
Rel(triptop, intern, "Stuurt boekingsgegevens")

@enduml